name: surf_dart_courses_template
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/me.jpg
    - assets/images/ufo.svg
    - assets/images/star.svg
    - assets/images/rocket.svg
  fonts:
    - family: Bauhas
      fonts:
        - asset: assets/fonts/bauhas.ttf
    - family: Disket
      fonts:
      - asset: assets/fonts/Disket-Mono-Regular.ttf
      - asset: assets/fonts/Disket-Mono-Bold.ttf
        weight: 700
    - family: Cyberpunk
      fonts:
        - asset: assets/fonts/Cyberpunk.ttf
    - family: Adventure
      fonts:
        - asset: assets/fonts/Adventure.ttf
  uses-material-design: true